# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.srcs/sources_1/ip/ila_vs_count/ila_vs_count.xci
# IP: The module: 'ila_vs_count' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.gen/sources_1/ip/ila_vs_count/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_vs_count'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.gen/sources_1/ip/ila_vs_count/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_vs_count'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.gen/sources_1/ip/ila_vs_count/ila_vs_count_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_vs_count'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.srcs/sources_1/ip/ila_vs_count/ila_vs_count.xci
# IP: The module: 'ila_vs_count' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.gen/sources_1/ip/ila_vs_count/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_vs_count'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.gen/sources_1/ip/ila_vs_count/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_vs_count'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.gen/sources_1/ip/ila_vs_count/ila_vs_count_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_vs_count'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
