# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.srcs/sources_1/ip/jtag_axi_0/jtag_axi_0.xci
# IP: The module: 'jtag_axi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.gen/sources_1/ip/jtag_axi_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.gen/sources_1/ip/jtag_axi_0/jtag_axi_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.srcs/sources_1/ip/jtag_axi_0/jtag_axi_0.xci
# IP: The module: 'jtag_axi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.gen/sources_1/ip/jtag_axi_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alex/SecurityReconfiguration/dfx_genesys/dfx_genesys.gen/sources_1/ip/jtag_axi_0/jtag_axi_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
